title: new-language.guide
description: >
  How do I start a project in a new language?
baseurl: ""
url: "https://new-language.guide"

port: 8080
host: 0.0.0.0
show_dir_listing: false

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: pretty

collections:
  guides:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: page

