version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
            - gems-

      - run: bundle install

      - save_cache:
          paths:
            - ./venv
          key: gems-{{ checksum "Gemfile.lock" }}

      - run: bundle exec jekyll build

      - run:
          name: Deploy to Heroku
          command: git push heroku ${CIRCLE_BRANCH}:master -f

